// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_treasure_hunter = "CgkIyriH1Y4ZEAIQBQ"; // <GPGSID>
        public const string achievement_adventurer = "CgkIyriH1Y4ZEAIQAQ"; // <GPGSID>
        public const string achievement_new_job = "CgkIyriH1Y4ZEAIQBg"; // <GPGSID>
        public const string achievement_allseeing_eye = "CgkIyriH1Y4ZEAIQCg"; // <GPGSID>
        public const string achievement_laser_party = "CgkIyriH1Y4ZEAIQCQ"; // <GPGSID>
        public const string achievement_0 = "CgkIyriH1Y4ZEAIQDA"; // <GPGSID>
        public const string achievement_unlucky = "CgkIyriH1Y4ZEAIQBA"; // <GPGSID>
        public const string achievement_defender = "CgkIyriH1Y4ZEAIQBw"; // <GPGSID>
        public const string achievement_bang = "CgkIyriH1Y4ZEAIQAw"; // <GPGSID>
        public const string achievement_panic_at_the_party = "CgkIyriH1Y4ZEAIQCA"; // <GPGSID>
        public const string leaderboard_second_cave = "CgkIyriH1Y4ZEAIQDg"; // <GPGSID>
        public const string leaderboard_first_cave = "CgkIyriH1Y4ZEAIQDQ"; // <GPGSID>
        public const string achievement_fisher = "CgkIyriH1Y4ZEAIQCw"; // <GPGSID>
        public const string leaderboard_third_cave = "CgkIyriH1Y4ZEAIQDw"; // <GPGSID>

}

